Jy/login
SCCPJT/instagram_clone_aos_app pull request #6
Opened 2021-03-23 13:21 UTC by JooYoung1121

# Description

로그인 기능 구현

Fixes # (issue)

## Proposed Changes

- menifest수정
- 로그인 액티비티 수정
- gradle파일 수정

## Additional Info

** any additional useful context or info **

2021-03-24 07:24 UTC, DaleBae requested changes
main 브랜치로 설정되어 있습니다. develop 브랜치로 변경해주세요.

2021-03-24 07:28 UTC, DaleBae commented
gitignore를 다시 적용해주세요!
https://cjh5414.github.io/gitignore-update/

2021-03-24 07:35 UTC, DaleBae reviewed
고생하셨습니다! 서버와 통신해서 동작하는 부분은 참고하겠습니다.

2021-03-24 07:35 UTC, DaleBae commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/LoginActivity.kt
> +}
No new line at the end of the file

2021-03-24 07:35 UTC, DaleBae commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/LoginActivity.kt
> +            val Body = HashMap<String,String>()
변수명 코드스타일은 하나로 통일해주시면 좋을 것 같습니다.
```kotlin
val retrofitService
val text_email
```
2가지가 공존합니다.

2021-03-24 07:35 UTC, DaleBae commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/LoginService.kt
> +
empty line

2021-03-24 07:35 UTC, DaleBae commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/MainActivity.kt
>          //setContentView(R.layout.post_explanation)
Please remove unused comments

2021-03-24 07:35 UTC, DaleBae commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/MainActivity.kt
> +        setContentView(R.layout.posting)
MainActivity의 ContentView를 변경하신 이유가 있나요?

2021-03-24 07:39 UTC, JooYoung1121 commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/MainActivity.kt
> +        setContentView(R.layout.posting)
bottom navigation 이 동작을 안해서 테스트할 수 없어서 일단은 임의 레이아웃으로 테스트햇습니다.

2021-03-24 07:40 UTC, JooYoung1121 commented on InstagramClone/app/src/main/java/com/cookandroid/instagramclone/MainActivity.kt
>          //setContentView(R.layout.post_explanation)
이부분은 상도형 담당이라 일단 유지했습니다

2021-03-25 12:46 UTC, sangdo913 approved these changes
LGTM

2021-03-25 13:09 UTC, merged